In [ ]:
# Parameters
parser = argparse.ArgumentParser(description = 'Parse parameters for multilocus GWAS')
parser.add_argument('-p', '--phenotype', help = 'Path to phenotype file. CSV file with accession ID in forst column, phenptype values in second column. Filename is used as phenotype name.', required = True)
parser.add_argument('-g', '--genotype', help = 'Path to the SNP matrix in HDF5 format.', required=True)
parser.add_argument('-k', '--kinship', help = 'Path to the kinship matrix in HDF5 format.', required = True)
parser.add_argument('-m', '--maf', help = 'Specify the minor allele frequecny cut-off. Default is set to 0.05', default = 0.05)
parser.add_argument('-o', '--outDir', help = 'Specify the output directory. All results will be saved in this directory.', required = True)
args = parser.parse_args()

In [1]:
!pip install limix

Defaulting to user installation because normal site-packages is not writeable
Collecting limix
  Using cached limix-3.0.4-py3-none-any.whl
Requirement already satisfied: appdirs>=1.4.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (1.4.4)
Requirement already satisfied: asciitree>=0.3.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.3)
Requirement already satisfied: bgen-reader>=3.0.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.0.8)
Requirement already satisfied: blessings>=1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7)
Requirement already satisfied: brent-search>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: click>=7.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (8.0.3)
Requirement already satisfied: colorama>=0.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (0.4.4)
Requirement already satisfied: dask>=2.5.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (2021.10.0)
Requirement already satisfied: glimix-core>=3.1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.1.13)
Requirement already satisfied: h5py>=2.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.13.0)
Requirement already satisfied: humanfriendly>=4.18 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (10.0)
Requirement already satisfied: joblib>=0.13.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.3.2)
Requirement already satisfied: limix-plot>=0.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.1.2)
Requirement already satisfied: loguru>=0.3.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.7.2)
Requirement already satisfied: matplotlib>=3.0.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (3.4.3)
Requirement already satisfied: monotonic>=1.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6)
Requirement already satisfied: ndarray-listener>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: netcdf4>=1.5.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7.2)
Requirement already satisfied: numba>=0.43.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.60.0)
Requirement already satisfied: numpy-sugar>=1.4.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.5.3)
Requirement already satisfied: numpy>=1.17.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.2)
Requirement already satisfied: optimix>=3.0.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.0.4)
Requirement already satisfied: pandas-plink>=2.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.9)
Requirement already satisfied: pandas!=0.25.0rc0,>=0.24.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.3)
Requirement already satisfied: pytest-doctestplus>=0.4.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.4.0)
Requirement already satisfied: pytest-remfiles>=0.0.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.0.2)
Requirement already satisfied: pytest>=4.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (6.2.4)
Requirement already satisfied: qtoml>=0.2.4 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.1)
Requirement already satisfied: scikit-learn>=0.20.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6.1)
Requirement already satisfied: scipy>=1.2.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.13.1)
Requirement already satisfied: seaborn>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.13.0)
Requirement already satisfied: setuptools>=41.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (58.0.4)
Requirement already satisfied: statsmodels>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.14.0)
Requirement already satisfied: tqdm>=4.31.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.64.1)
Requirement already satisfied: xarray>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2024.7.0)
Requirement already satisfied: cachetools>=3.1.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (5.5.2)
Requirement already satisfied: cbgen>=1.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.0.6)
Requirement already satisfied: requests>=1.25.8 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (2.26.0)
Requirement already satisfied: texttable>=1.6.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.7.0)
Requirement already satisfied: six in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from blessings>=1.7->limix) (1.16.0)
Requirement already satisfied: cloudpickle>=1.1.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (2.0.0)
Requirement already satisfied: fsspec>=0.6.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (2021.8.1)
Requirement already satisfied: packaging>=20.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (25.0)
Requirement already satisfied: partd>=0.3.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (1.2.0)
Requirement already satisfied: pyyaml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (6.0)
Requirement already satisfied: toolz>=0.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (0.11.1)
Requirement already satisfied: liknorm>=1.2.8 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from glimix-core>=3.1.7->limix) (1.2.10)
Requirement already satisfied: adjustText>=0.7.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (1.3.0)
Requirement already satisfied: Pillow>=6.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (2.8.2)
Requirement already satisfied: cftime in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (1.6.4.post1)
Requirement already satisfied: certifi in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (2021.10.8)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from numba>=0.43.1->limix) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2021.3)
Requirement already satisfied: tzdata>=2022.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2023.3)
Requirement already satisfied: Deprecated>=1.2.6 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (1.2.18)
Requirement already satisfied: cffi>=1.14.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (1.14.6)
Requirement already satisfied: zstandard>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (0.23.0)
Requirement already satisfied: attrs>=19.2.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (21.2.0)
Requirement already satisfied: iniconfig in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.1.1)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.13.1)
Requirement already satisfied: py>=1.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.10.0)
Requirement already satisfied: toml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.10.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from scikit-learn>=0.20.3->limix) (3.2.0)
Requirement already satisfied: patsy>=0.5.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from statsmodels>=0.9.0->limix) (0.5.3)
Requirement already satisfied: pooch in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.8.2)
Requirement already satisfied: urllib3>=1.26 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.26.7)
Requirement already satisfied: pycparser in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cffi>=1.14.3->pandas-plink>=2.0.1->limix) (2.20)
Requirement already satisfied: wrapt<2,>=1.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from Deprecated>=1.2.6->pandas-plink>=2.0.1->limix) (1.12.1)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/packaging-25.0.dist-info/METADATA'

In [2]:
from limix.qtl import scan
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'limix'

In [ ]:
import numpy as np

In [9]:
!pip install limix

Defaulting to user installation because normal site-packages is not writeable
Collecting limix
  Using cached limix-3.0.4-py3-none-any.whl
Requirement already satisfied: appdirs>=1.4.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (1.4.4)
Requirement already satisfied: asciitree>=0.3.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.3)
Requirement already satisfied: bgen-reader>=3.0.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.0.8)
Requirement already satisfied: blessings>=1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7)
Requirement already satisfied: brent-search>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: click>=7.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (8.0.3)
Requirement already satisfied: colorama>=0.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (0.4.4)
Requirement already satisfied: dask>=2.5.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (2021.10.0)
Requirement already satisfied: glimix-core>=3.1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.1.13)
Requirement already satisfied: h5py>=2.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.13.0)
Requirement already satisfied: humanfriendly>=4.18 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (10.0)
Requirement already satisfied: joblib>=0.13.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.3.2)
Requirement already satisfied: limix-plot>=0.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.1.2)
Requirement already satisfied: loguru>=0.3.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.7.2)
Requirement already satisfied: matplotlib>=3.0.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (3.4.3)
Requirement already satisfied: monotonic>=1.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6)
Requirement already satisfied: ndarray-listener>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: netcdf4>=1.5.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7.2)
Requirement already satisfied: numba>=0.43.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.60.0)
Requirement already satisfied: numpy-sugar>=1.4.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.5.3)
Requirement already satisfied: numpy>=1.17.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.2)
Requirement already satisfied: optimix>=3.0.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.0.4)
Requirement already satisfied: pandas-plink>=2.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.9)
Requirement already satisfied: pandas!=0.25.0rc0,>=0.24.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.3)
Requirement already satisfied: pytest-doctestplus>=0.4.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.4.0)
Requirement already satisfied: pytest-remfiles>=0.0.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.0.2)
Requirement already satisfied: pytest>=4.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (6.2.4)
Requirement already satisfied: qtoml>=0.2.4 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.1)
Requirement already satisfied: scikit-learn>=0.20.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6.1)
Requirement already satisfied: scipy>=1.2.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.13.1)
Requirement already satisfied: seaborn>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.13.0)
Requirement already satisfied: setuptools>=41.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (58.0.4)
Requirement already satisfied: statsmodels>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.14.0)
Requirement already satisfied: tqdm>=4.31.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.64.1)
Requirement already satisfied: xarray>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2024.7.0)
Requirement already satisfied: cachetools>=3.1.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (5.5.2)
Requirement already satisfied: cbgen>=1.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.0.6)
Requirement already satisfied: requests>=1.25.8 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (2.26.0)
Requirement already satisfied: texttable>=1.6.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.7.0)
Requirement already satisfied: six in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from blessings>=1.7->limix) (1.16.0)
Requirement already satisfied: cloudpickle>=1.1.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (2.0.0)
Requirement already satisfied: fsspec>=0.6.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (2021.8.1)
Requirement already satisfied: packaging>=20.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (25.0)
Requirement already satisfied: partd>=0.3.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (1.2.0)
Requirement already satisfied: pyyaml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (6.0)
Requirement already satisfied: toolz>=0.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask>=2.5.0->dask[array,dataframe]>=2.5.0->limix) (0.11.1)
Requirement already satisfied: liknorm>=1.2.8 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from glimix-core>=3.1.7->limix) (1.2.10)
Requirement already satisfied: adjustText>=0.7.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (1.3.0)
Requirement already satisfied: Pillow>=6.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (2.8.2)
Requirement already satisfied: cftime in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (1.6.4.post1)
Requirement already satisfied: certifi in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (2021.10.8)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from numba>=0.43.1->limix) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2021.3)
Requirement already satisfied: tzdata>=2022.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2023.3)
Requirement already satisfied: Deprecated>=1.2.6 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (1.2.18)
Requirement already satisfied: cffi>=1.14.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (1.14.6)
Requirement already satisfied: zstandard>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (0.23.0)
Requirement already satisfied: attrs>=19.2.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (21.2.0)
Requirement already satisfied: iniconfig in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.1.1)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.13.1)
Requirement already satisfied: py>=1.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.10.0)
Requirement already satisfied: toml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.10.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from scikit-learn>=0.20.3->limix) (3.2.0)
Requirement already satisfied: patsy>=0.5.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from statsmodels>=0.9.0->limix) (0.5.3)
Requirement already satisfied: pooch in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.8.2)
Requirement already satisfied: urllib3>=1.26 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.26.7)
Requirement already satisfied: pycparser in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cffi>=1.14.3->pandas-plink>=2.0.1->limix) (2.20)
Requirement already satisfied: wrapt<2,>=1.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from Deprecated>=1.2.6->pandas-plink>=2.0.1->limix) (1.12.1)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/packaging-25.0.dist-info/METADATA'

In [10]:
## Step 1. Phenotype load 
import pandas as pd

pheno_path = "/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/phenotype.txt"  # Phenotype load 
pheno = pd.read_csv(pheno_path, index_col=0, sep="\t", header=None)

print(pheno.head())
print("Shape:", pheno.shape)

              1         2
0
10010  0.024980 -0.324621
1002  -0.049857 -0.024401
108   -0.033401  1.064215
14319 -0.040161  0.492114
15560 -0.016326  0.265559
Shape: (266, 2)

In [17]:
import h5py
import numpy as np

geno_file = '/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/1163g.179kB.prior15.gauss4.ts99.5.BIALLELIC.filtered.vcf.hdf5'

with h5py.File(geno_file, 'r') as f:
    samples = f['samples'][:]
    samples = np.array([s.decode() if isinstance(s, bytes) else s for s in samples])
    
    GT = f['calldata/GT'][:]  # (variants, samples, ploidy=2)
    G = GT.sum(axis=2)  # Convert to 0/1/2 genotype dosage

# Make sure pheno index is str
pheno.index = pheno.index.astype(str)

# Find intersection
common_accessions = [acn for acn in pheno.index if acn in samples]
if not common_accessions:
    raise ValueError("No matching accessions between phenotype and genotype!")

# Get indices
acn_indices = [np.where(samples == acn)[0][0] for acn in common_accessions]
G = G[:, acn_indices]
samples_matched = samples[acn_indices]
pheno = pheno.loc[samples_matched]

In [18]:
G.shape

(7051412, 266)

In [19]:
## Filtering by MAF
# Count alternate alleles (AC1) and reference alleles (AC0)
AC1 = G.sum(axis=1)
AC0 = G.shape[1] * 2 - AC1  # diploid: 2 alleles per sample

# Stack for MAF calculation
AC = np.vstack((AC0, AC1))
MAC = np.min(AC, axis=0)  # Minor allele count
MAF = MAC / (G.shape[1] * 2)  # Minor allele frequency

# Filter SNPs with MAF >= 5%
#SNP_indices = np.where(MAF >= 0.00)[0]
#G = G[SNP_indices, :]
G = G.T  # Now shape: (samples, SNPs)
G.shape

(266, 4014812)

In [9]:
## Kinship and check 
import numpy as np
import pandas as pd

# 1. Load kinship matrix
K = np.loadtxt('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel')

# 2. Load IDs file - now skipping the header row
ids = pd.read_csv('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel.id',
                  delimiter='\s+',
                  header=0,  # This tells pandas to use the first row as header
                  names=['IID'])  # This names the column

# Convert IDs to strings
ids['IID'] = ids['IID'].astype(str)
pheno_index = pheno.index.astype(str)

# Create index mapping (now without the "IID" header issue)
id_to_index = dict(zip(ids['IID'], range(len(ids))))

# Get indices
acn_indices = [id_to_index[acn] for acn in pheno_index]

# Subset the kinship matrix
K_sub = K[acn_indices, :][:, acn_indices]

print("Original matrix shape:", K.shape)
print("Subsetted matrix shape:", K_sub.shape)

Original matrix shape: (266, 266)
Subsetted matrix shape: (266, 266)

In [21]:
import numpy as np

# G: (samples, SNPs)
# pheno: (samples, 2)
# K_sub: (samples, samples)

Y = pheno.values  # shape: (samples, 2)
X = np.ones((Y.shape[0], 1))  # Intercept only

print("Genotype shape:", G.shape)
print("Phenotype shape:", Y.shape)
print("Kinship shape:", K_sub.shape)

Genotype shape: (266, 4014812)
Phenotype shape: (266, 2)
Kinship shape: (266, 266)

In [1]:
import limix
print(limix.__version__)

ModuleNotFoundError: No module named 'limix'

In [32]:
from limix.qtl import scan
help(scan)

Help on function scan in module limix.qtl._scan:

scan(G, Y, lik='normal', K=None, M=None, idx=None, A=None, A0=None, A1=None, verbose=True)
    Multi-trait association and interaction testing via linear mixed models.

    Let n, c, and p be the number of samples, covariates, and traits, respectively.
    The outcome variable Y is a n×p matrix distributed according to ::

        vec(Y) ~ N((A ⊗ M) vec(𝚨), K₀ = C₀ ⊗ K + C₁ ⊗ I) under H₀.

    A and M are design matrices of dimensions p×p and n×c provided by the user,
    where X is the usual matrix of covariates commonly used in single-trait models.
    𝚨 is a c×p matrix of fixed-effect sizes per trait.
    C₀ and C₁ are both symmetric matrices of dimensions p×p, for which C₁ is
    guaranteed by our implementation to be of full rank.
    The parameters of the H₀ model are the matrices 𝚨, C₀, and C₁.

    The additional models H₁ and H₂ are define as ::

        vec(Y) ~ N((A ⊗ M) vec(𝚨) + (A₀ ⊗ Gᵢ) vec(𝚩₀), s⋅K₀)

    and ::

        vec(Y) ~ N((A ⊗ M) vec(𝚨) + (A₀ ⊗ Gᵢ) vec(𝚩₀) + (A₁ ⊗ Gᵢ) vec(𝚩₁), s⋅K₀)

    It performs likelihood-ratio tests for the following cases, where the first
    hypothesis is the null one while the second hypothesis is the alternative one:

    - H₀ vs H₁: testing for vec(𝚩₀) ≠ 𝟎 while vec(𝚩₁) = 𝟎
    - H₀ vs H₂: testing for [vec(𝚩₀) vec(𝚩₁)] ≠ 𝟎
    - H₁ vs H₂: testing for vec(𝚩₁) ≠ 𝟎

    It supports generalized linear mixed models (GLMM) when a single trait is used.
    In this case, the following likelihoods are implemented:

    - Bernoulli
    - Probit
    - Binomial
    - Poisson

    Formally, let p(𝜇) be one of the supported probability distributions where 𝜇 is
    its mean. The H₀ model is defined as follows::

        yᵢ ∼ p(𝜇ᵢ=g(zᵢ)) for 𝐳 ∼ 𝓝(..., ...).

    g(⋅) is the corresponding canonical link function for the Bernoulli, Binomial, and
    Poisson likelihoods. The Probit likelihood, on the other hand, is a Bernoulli
    likelihood with probit link function.

    Parameters
    ----------
    G : n×m array_like
        Genetic candidates.
    Y : n×p array_like
        Rows are samples and columns are phenotypes.
    lik : tuple, "normal", "bernoulli", "probit", "binomial", "poisson"
        Sample likelihood describing the residual distribution.
        Either a tuple or a string specifying the likelihood is required. The Normal,
        Bernoulli, Probit, and Poisson likelihoods can be selected by providing a
        string. Binomial likelihood on the other hand requires a tuple because of the
        number of trials: ``("binomial", array_like)``. Defaults to ``"normal"``.
    K : n×n array_like
        Sample covariance, often the so-called kinship matrix.
    M : n×c array_like
        Covariates matrix.
    idx : list
        List of candidate indices that defines the set of candidates to be used in the
        tests.
    A : p×p array_like
        Symmetric trait-by-trait design matrix.
    A0 : p×p₀ array_like, optional
        Matrix A₀, possibility a non-symmetric one. If ``None``, it defines an empty
        matrix, p₀=0. Defaults to ``None``.
    A1 : p×p₁ array_like, optional
        Matrix A₁, possibility a non-symmetric one. If ``None``, it defines an identity
        matrix, p₀=p. Defaults to ``None``.
    verbose : bool, optional
        ``True`` to display progress and summary; ``False`` otherwise.

    Returns
    -------
    result : :class:`limix.qtl._result.STScanResult`, :class:`limix.qtl._result.MTScanResult`
        P-values, log of marginal likelihoods, effect sizes, and associated statistics.

    Examples
    --------
    .. doctest::

        >>> from limix.qtl import scan
        >>> from numpy import reshape, kron, eye
        >>> from numpy import concatenate
        >>> from numpy.random import RandomState
        >>> import scipy.stats as st
        >>> from limix.qc import normalise_covariance
        >>>
        >>> def vec(x):
        ...     return reshape(x, (-1,) + x.shape[2:], order="F")
        >>>
        >>> def unvec(x, shape):
        ...     return reshape(x, shape, order="F")
        >>>
        >>> random = RandomState(0)
        >>> n = 30
        >>> ntraits = 2
        >>> ncovariates = 3
        >>>
        >>> A = random.randn(ntraits, ntraits)
        >>> A = A @ A.T
        >>> M = random.randn(n, ncovariates)
        >>>
        >>> C0 = random.randn(ntraits, ntraits)
        >>> C0 = C0 @ C0.T
        >>>
        >>> C1 = random.randn(ntraits, ntraits)
        >>> C1 = C1 @ C1.T
        >>>
        >>> G = random.randn(n, 4)
        >>>
        >>> A0 = random.randn(ntraits, 1)
        >>> A1 = random.randn(ntraits, 2)
        >>> A01 = concatenate((A0, A1), axis=1)
        >>>
        >>> K = random.randn(n, n + 1)
        >>> K = normalise_covariance(K @ K.T)
        >>>
        >>> beta = vec(random.randn(ntraits, ncovariates))
        >>> alpha = vec(random.randn(A01.shape[1], G.shape[1]))
        >>>
        >>> mvn = st.multivariate_normal
        >>> m = kron(A, M) @ beta + kron(A01, G) @ alpha
        >>> Y = unvec(mvn(m, kron(C0, K) + kron(C1, eye(n))).rvs(), (n, -1))
        >>>
        >>> idx = [[0, 1], 2, [3]]
        >>> r = scan(G, Y, idx=idx, K=K, M=M, A=A, A0=A0, A1=A1, verbose=False)

    .. doctest::

        >>> from numpy import dot, exp, sqrt, ones
        >>> from numpy.random import RandomState
        >>> from pandas import DataFrame
        >>> import pandas as pd
        >>> from limix.qtl import scan
        >>>
        >>> random = RandomState(1)
        >>> pd.options.display.float_format = "{:9.6f}".format
        >>>
        >>> n = 30
        >>> p = 3
        >>> samples_index = range(n)
        >>>
        >>> M = DataFrame(dict(offset=ones(n), age=random.randint(10, 60, n)))
        >>> M.index = samples_index
        >>>
        >>> X = random.randn(n, 100)
        >>> K = dot(X, X.T)
        >>>
        >>> candidates = random.randn(n, p)
        >>> candidates = DataFrame(candidates, index=samples_index,
        ...                                    columns=['rs0', 'rs1', 'rs2'])
        >>>
        >>> y = random.poisson(exp(random.randn(n)))
        >>>
        >>> result = scan(candidates, y, 'poisson', K, M=M, verbose=False)
        >>>
        >>> result.stats  # doctest: +FLOAT_CMP
                   lml0       lml2  dof20    scale2      pv20
        test
        0    -48.720890 -48.536860      1  0.943532  0.544063
        1    -48.720890 -47.908341      1  0.904814  0.202382
        2    -48.720890 -48.534754      1  0.943400  0.541768
        >>> print(result)  # doctest: +FLOAT_CMP
        Hypothesis 0
        ------------
        <BLANKLINE>
        𝐳 ~ 𝓝(𝙼𝜶, 0.000⋅𝙺 + 0.788⋅𝙸) for yᵢ ~ Poisson(λᵢ=g(zᵢ)) and g(x)=eˣ
        <BLANKLINE>
        M     = ['offset' 'age']
        𝜶     = [ 0.39528889 -0.00556797]
        se(𝜶) = [0.50173695 0.01505240]
        lml   = -48.720890273519444
        <BLANKLINE>
        Hypothesis 2
        ------------
        <BLANKLINE>
        𝐳 ~ 𝓝(𝙼𝜶 + G𝛃, s(0.000⋅𝙺 + 0.788⋅𝙸)) for yᵢ ~ Poisson(λᵢ=g(zᵢ)) and g(x)=eˣ
        <BLANKLINE>
                  lml       cov. effsizes   cand. effsizes
        --------------------------------------------------
        mean   -4.833e+01       2.393e-01       -1.966e-01
        std     3.623e-01       2.713e-01        1.028e-01
        min    -4.854e+01      -8.490e-03       -3.151e-01
        25%    -4.854e+01      -7.684e-03       -2.295e-01
        50%    -4.853e+01       2.243e-01       -1.439e-01
        75%    -4.822e+01       4.725e-01       -1.374e-01
        max    -4.791e+01       5.255e-01       -1.309e-01
        <BLANKLINE>
        Likelihood-ratio test p-values
        ------------------------------
        <BLANKLINE>
               𝓗₀ vs 𝓗₂
        ----------------
        mean   4.294e-01
        std    1.966e-01
        min    2.024e-01
        25%    3.721e-01
        50%    5.418e-01
        75%    5.429e-01
        max    5.441e-01
        >>> from numpy import zeros
        >>>
        >>> nsamples = 50
        >>>
        >>> X = random.randn(nsamples, 2)
        >>> G = random.randn(nsamples, 100)
        >>> K = dot(G, G.T)
        >>> ntrials = random.randint(1, 100, nsamples)
        >>> z = dot(G, random.randn(100)) / sqrt(100)
        >>>
        >>> successes = zeros(len(ntrials), int)
        >>> for i, nt in enumerate(ntrials):
        ...     for _ in range(nt):
        ...         successes[i] += int(z[i] + 0.5 * random.randn() > 0)
        >>>
        >>> result = scan(X, successes, ("binomial", ntrials), K, verbose=False)
        >>> print(result)  # doctest: +FLOAT_CMP
        Hypothesis 0
        ------------
        <BLANKLINE>
        𝐳 ~ 𝓝(𝙼𝜶, 0.152⋅𝙺 + 1.738⋅𝙸) for yᵢ ~ Binom(μᵢ=g(zᵢ), nᵢ) and g(x)=1/(1+e⁻ˣ)
        <BLANKLINE>
        M     = ['offset']
        𝜶     = [0.40956942]
        se(𝜶) = [0.55141166]
        lml   = -142.80784719977515
        <BLANKLINE>
        Hypothesis 2
        ------------
        <BLANKLINE>
        𝐳 ~ 𝓝(𝙼𝜶 + G𝛃, s(0.152⋅𝙺 + 1.738⋅𝙸)) for yᵢ ~ Binom(μᵢ=g(zᵢ), nᵢ) and g(x)=1/(1+e⁻ˣ)
        <BLANKLINE>
                  lml       cov. effsizes   cand. effsizes
        --------------------------------------------------
        mean   -1.425e+02       3.701e-01        2.271e-01
        std     4.110e-01       2.296e-02        5.680e-01
        min    -1.427e+02       3.539e-01       -1.745e-01
        25%    -1.426e+02       3.620e-01        2.631e-02
        50%    -1.425e+02       3.701e-01        2.271e-01
        75%    -1.423e+02       3.782e-01        4.279e-01
        max    -1.422e+02       3.864e-01        6.287e-01
        <BLANKLINE>
        Likelihood-ratio test p-values
        ------------------------------
        <BLANKLINE>
               𝓗₀ vs 𝓗₂
        ----------------
        mean   4.959e-01
        std    3.362e-01
        min    2.582e-01
        25%    3.771e-01
        50%    4.959e-01
        75%    6.148e-01
        max    7.336e-01

    Notes
    -----
    It will raise a ``ValueError`` exception if non-finite values are passed. Please,
    refer to the :func:`limix.qc.mean_impute` function for missing value imputation.

In [54]:
G = np.asarray(G)
Y = np.asarray(Y)
K = np.asarray(K_sub)  # or whatever your kinship variable is called

In [59]:
G.shape
Y.shape
K.shape

(266, 266)

In [ ]:
!pip install packaging
!pip install limix
!pip install --force-reinstall --no-deps packaging==25.0

:

In [ ]:
import packaging
print(packaging.__version__)

23.1

In [ ]:

# G: (samples, SNPs)
# Y: (samples, traits)
# K_sub: (samples, samples)
# X: (samples, covariates)  # intercept

from limix.qtl import scan

result = scan(
    G=G,
    Y=Y,
    lik='normal',
    K=K,
    verbose=True
)

:

In [5]:
## Kinship and check 
import numpy as np
import pandas as pd

# 1. Load kinship matrix
K = np.loadtxt('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel')

# 2. Load IDs file - now skipping the header row
ids = pd.read_csv('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel.id',
                  delimiter='\s+',
                  header=0,  # This tells pandas to use the first row as header
                  names=['IID'])  # This names the column

# Convert IDs to strings
ids['IID'] = ids['IID'].astype(str)
pheno_index = pheno.index.astype(str)

# Create index mapping (now without the "IID" header issue)
id_to_index = dict(zip(ids['IID'], range(len(ids))))

# Get indices
acn_indices = [id_to_index[acn] for acn in pheno_index]

# Subset the kinship matrix
K_sub = K[acn_indices, :][:, acn_indices]

print("Original matrix shape:", K.shape)
print("Subsetted matrix shape:", K_sub.shape)

Original matrix shape: (266, 266)
Subsetted matrix shape: (266, 266)

In [9]:
import h5py

In [6]:
import h5py
import numpy as np
import pandas as pd

# 1. First check phenotype file
print("Checking phenotype file...")
pheno = pd.read_csv('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/phenotype.txt', index_col=0)
print("Phenotype data shape:", pheno.shape)
print("First few rows of phenotype data:")
print(pheno.head())
print("\nPhenotype index example:", pheno.index[:5])

# 2. Check HDF5 file structure
print("\nChecking HDF5 file structure...")
with h5py.File('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/1163g.179kB.prior15.gauss4.ts99.5.BIALLELIC.filtered.vcf.hdf5', 'r') as f:
    print("Available keys:", list(f.keys()))
    # Print structure
    def print_structure(name, obj):
        print(f"Found object: {name}, Type: {type(obj)}")
        if isinstance(obj, h5py.Dataset):
            print(f"    Shape: {obj.shape}")
            print(f"    dtype: {obj.dtype}")
    
    f.visititems(print_structure)

# 3. Check kinship files
print("\nChecking kinship files...")
# Read kinship IDs
ids = pd.read_csv('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel.id',
                  delimiter='\s+',
                  header=None)
print("Kinship IDs shape:", ids.shape)
print("First few kinship IDs:")
print(ids.head())

# Try to read a small part of the kinship matrix
K = np.loadtxt('/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/kinship.rel')
print("\nKinship matrix shape:", K.shape)

Checking phenotype file...
Phenotype data shape: (265, 0)
First few rows of phenotype data:
Empty DataFrame
Columns: []
Index: [1002	-0.0498567588390866	-0.0244012147190962, 108	-0.0334012310597945	1.06421505652304, 14319	-0.0401607745727262	0.492114242290163, 15560	-0.0163255979759414	0.265559225659471, 15592	-0.087685162558938	0.164224731244577]

Phenotype index example: Index(['1002\t-0.0498567588390866\t-0.0244012147190962',
       '108\t-0.0334012310597945\t1.06421505652304',
       '14319\t-0.0401607745727262\t0.492114242290163',
       '15560\t-0.0163255979759414\t0.265559225659471',
       '15592\t-0.087685162558938\t0.164224731244577'],
      dtype='object', name='10010\t0.0249804652996104\t-0.324620943956854')

Checking HDF5 file structure...
Available keys: ['calldata', 'samples', 'variants']
Found object: calldata, Type: <class 'h5py._hl.group.Group'>
Found object: calldata/AD, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266, 4)
    dtype: int16
Found object: calldata/DP, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: int16
Found object: calldata/GQ, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: int8
Found object: calldata/GT, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266, 2)
    dtype: int8
Found object: calldata/MIN_DP, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: int32
Found object: calldata/PGT, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: object
Found object: calldata/PID, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: object
Found object: calldata/PL, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266, 3)
    dtype: int32
Found object: calldata/RGQ, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266)
    dtype: int32
Found object: calldata/SB, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 266, 4)
    dtype: int32
Found object: samples, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (266,)
    dtype: object
Found object: variants, Type: <class 'h5py._hl.group.Group'>
Found object: variants/AC, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: int32
Found object: variants/AF, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: float32
Found object: variants/ALT, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: object
Found object: variants/AN, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: int32
Found object: variants/BaseQRankSum, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/CHROM, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: object
Found object: variants/ClippingRankSum, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/DP, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: int32
Found object: variants/DS, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/END, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: int32
Found object: variants/FILTER_LowQual, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_PASS, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP95.00to97.00, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP97.00to99.00, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP99.00to99.50, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP99.50to99.90, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP99.90to99.95, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP99.95to100.00, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FILTER_VQSRTrancheSNP99.95to100.00+, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/FS, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/HaplotypeScore, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/ID, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: object
Found object: variants/InbreedingCoeff, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/MLEAC, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: int32
Found object: variants/MLEAF, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: float32
Found object: variants/MQ, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/MQRankSum, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/NEGATIVE_TRAIN_SITE, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/POS, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: int32
Found object: variants/POSITIVE_TRAIN_SITE, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/QD, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/QUAL, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/REF, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: object
Found object: variants/ReadPosRankSum, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/SOR, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/VQSLOD, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: float32
Found object: variants/altlen, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412, 3)
    dtype: int32
Found object: variants/culprit, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: object
Found object: variants/is_snp, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: bool
Found object: variants/numalt, Type: <class 'h5py._hl.dataset.Dataset'>
    Shape: (7051412,)
    dtype: int32

Checking kinship files...
Kinship IDs shape: (267, 2)
First few kinship IDs:
      0      1
0  #FID    IID
1     0  10010
2     0   1002
3     0    108
4     0  14319

Kinship matrix shape: (266, 266)

In [7]:
pheno = pd.read_csv(
    '/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/phenotype.txt',
    sep='\t',  # Specify tab delimiter!
    index_col=0,
header=None)
print(pheno.shape)
print(pheno.head())

(266, 2)
              1         2
0
10010  0.024980 -0.324621
1002  -0.049857 -0.024401
108   -0.033401  1.064215
14319 -0.040161  0.492114
15560 -0.016326  0.265559

In [8]:
##Import genotype file
import h5py
import numpy as np

geno_file = '/groups/nordborg/projects/ddm1_resilencing/03_processing/006_gwas/all_plates_96w/limix_gwas/1163g.179kB.prior15.gauss4.ts99.5.BIALLELIC.filtered.vcf.hdf5'
with h5py.File(geno_file, 'r') as f:
    samples = f['samples'][:].astype(str)
    GT = f['calldata/GT'][:]  # shape: (variants, samples, 2)
    # Convert GT to 0/1/2 (sum of alleles)
    G = GT.sum(axis=2)  # shape: (variants, samples)

In [9]:
G.shape

(7051412, 266)

In [10]:
# Make sure pheno index and samples are both strings
pheno.index = pheno.index.astype(str)
samples = np.array([s.decode() if isinstance(s, bytes) else s for s in samples])

# Find indices of phenotype accessions in genotype samples
acn_indices = [np.where(samples == acn)[0][0] for acn in pheno.index if acn in samples]
G = G[:, acn_indices]
samples_matched = samples[acn_indices]
pheno = pheno.loc[samples_matched]

In [15]:
G.shape

(7051412, 266)

In [16]:
pheno

              1         2
0
10010  0.024980 -0.324621
1002  -0.049857 -0.024401
108   -0.033401  1.064215
14319 -0.040161  0.492114
15560 -0.016326  0.265559
...         ...       ...
9927   0.015342 -0.406540
9933   0.072331  0.145948
9938  -0.054522  0.056299
9972  -0.035694  0.254552
9981  -0.006467  1.217904

[266 rows x 2 columns]

In [11]:
## Filtering by MAF
AC1 = G.sum(axis=1)
AC0 = G.shape[1] * 2 - AC1  # diploid: 2 alleles per sample
AC = np.vstack((AC0, AC1))
MAC = np.min(AC, axis=0)
MAF = MAC / (G.shape[1] * 2)
SNP_indices = np.where(MAF >= 0.05)[0]
G = G[SNP_indices, :]

In [18]:
## Transpose
G = G.T  # Now shape: (samples, SNPs)
G.shape

(266, 943557)

In [12]:
K_sub

array([[ 1.21806e+00, -1.92633e-02, -2.79335e-02, ..., -2.86010e-02,
         9.76501e-04, -6.48333e-03],
       [-1.92633e-02,  9.89894e-01, -7.38143e-03, ..., -9.28916e-03,
        -4.21479e-03, -9.27230e-03],
       [-2.79335e-02, -7.38143e-03,  9.11266e-01, ...,  3.70257e-02,
        -8.81522e-03, -6.73866e-03],
       ...,
       [-2.86010e-02, -9.28916e-03,  3.70257e-02, ...,  7.68257e-01,
        -1.13460e-02, -9.31693e-04],
       [ 9.76501e-04, -4.21479e-03, -8.81522e-03, ..., -1.13460e-02,
         9.97550e-01,  9.34093e-03],
       [-6.48333e-03, -9.27230e-03, -6.73866e-03, ..., -9.31693e-04,
         9.34093e-03,  9.53047e-01]])

In [13]:
from limix.qtl import scan
from numpy import concatenate, newaxis
from numpy import eye
import random

A = np.matrix('0 1; 1 0')
A0 = np.ones((len(traits), 1)) 
A1 = np.eye(len(traits))

In [101]:
!pip install numpy==1.16.2

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.16.2
  Downloading numpy-1.16.2.zip (5.1 MB)
     |████████████████████████████████| 5.1 MB 17.4 MB/s eta 0:00:01
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /software/f2021/software/anaconda3/2021.11/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ys_myh3j
       cwd: /tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/
  Complete output (129 lines):
  Running from numpy source directory.
  /tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

  /bin/sh: 1: svnversion: not found
  non-existing path in 'numpy/distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

  /software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.linux-x86_64-3.9
  creating build/src.linux-x86_64-3.9/numpy
  creating build/src.linux-x86_64-3.9/numpy/distutils
  building library "npymath" sources
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize IntelFCompiler
  Could not locate executable ifort
  Could not locate executable ifc
  customize LaheyFCompiler
  Could not locate executable lf95
  customize PGroupFCompiler
  Could not locate executable pgfortran
  customize AbsoftFCompiler
  Could not locate executable f90
  Could not locate executable f77
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  Could not locate executable fort
  customize IntelItaniumFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  Could not locate executable g77
  customize G95FCompiler
  Could not locate executable g95
  customize PathScaleFCompiler
  Could not locate executable pathf95
  customize NAGFORCompiler
  Could not locate executable nagfor
  don't know how to compile Fortran code on platform 'posix'
  C compiler: gcc -pthread -B /software/f2021/software/anaconda3/2021.11/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /software/f2021/software/anaconda3/2021.11/include -I/software/f2021/software/anaconda3/2021.11/include -fPIC -O2 -isystem /software/f2021/software/anaconda3/2021.11/include -fPIC

  compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/software/f2021/software/anaconda3/2021.11/include/python3.9 -c'
  gcc: _configtest.c
  failure.
  removing: _configtest.c _configtest.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py", line 415, in <module>
      setup_package()
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py", line 407, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build.py", line 47, in run
      old_build.run(self)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 148, in run
      self.build_sources()
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 159, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 292, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 375, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 667, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  Running setup.py clean for numpy
  ERROR: Command errored out with exit status 1:
   command: /software/f2021/software/anaconda3/2021.11/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae
  Complete output (10 lines):
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for numpy
Failed to build numpy
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
    Running setup.py install for numpy ... error
    ERROR: Command errored out with exit status 1:
     command: /software/f2021/software/anaconda3/2021.11/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qm_4g28_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /users/elizaveta.grigoreva/.local/include/python3.9/numpy
         cwd: /tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/
    Complete output (136 lines):
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)


    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

    /bin/sh: 1: svnversion: not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/software/f2021/software/anaconda3/2021.11/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/software/f2021/software/anaconda3/2021.11/include']

    /software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize LaheyFCompiler
    Could not locate executable lf95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    Could not locate executable fort
    customize IntelItaniumFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PathScaleFCompiler
    Could not locate executable pathf95
    customize NAGFORCompiler
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    C compiler: gcc -pthread -B /software/f2021/software/anaconda3/2021.11/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /software/f2021/software/anaconda3/2021.11/include -I/software/f2021/software/anaconda3/2021.11/include -fPIC -O2 -isystem /software/f2021/software/anaconda3/2021.11/include -fPIC

    compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/software/f2021/software/anaconda3/2021.11/include/python3.9 -c'
    gcc: _configtest.c
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py", line 415, in <module>
        setup_package()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/setup.py", line 407, in setup_package
        setup(**metadata)
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/software/f2021/software/anaconda3/2021.11/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 159, in build_sources
        self.build_library_sources(*libname_info)
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 292, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/tmp/pip-install-42pfms43/numpy_67c7d0f28f8c4bba87304494709bb1ae/numpy/distutils/command/build_src.py", line 375, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
  Rolling back uninstall of numpy
  Moving to /users/elizaveta.grigoreva/.local/bin/f2py
   from /tmp/pip-uninstall-p9g0ptp9/f2py
  Moving to /users/elizaveta.grigoreva/.local/bin/numpy-config
   from /tmp/pip-uninstall-p9g0ptp9/numpy-config
  Moving to /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/numpy-2.0.2.dist-info/
   from /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/~umpy-2.0.2.dist-info
  Moving to /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/numpy.libs/
   from /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/~%mpy.libs
  Moving to /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/numpy/
   from /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/~=mpy

In [58]:
# Quick data check
print("\nData check:")
print(f"G shape: {G.shape}")
print(f"K shape: {K_sub.shape}")
print(f"Phenotype shape: {pheno.shape}")

# Check for any obvious issues
print("\nData validation:")
print(f"G contains NaN: {np.isnan(G).any()}")
print(f"K contains NaN: {np.isnan(K_sub).any()}")
print(f"Phenotype contains NaN: {np.isnan(pheno).any()}")

Data check:
G shape: (266, 943557)
K shape: (266, 266)
Phenotype shape: (266, 2)

Data validation:
G contains NaN: False
K contains NaN: False
Phenotype contains NaN: 1    False
2    False
dtype: bool

In [59]:
import limix
import numpy as np
import pandas as pd

def run_gwas_simple(G, K, phenotype, output_prefix="gwas_results"):
    """
    Run GWAS using Limix (using correct interface)

    Parameters:
    -----------
    G : numpy array
        Genotype matrix (samples × SNPs)
    K : numpy array
        Kinship matrix (samples × samples)
    phenotype : numpy array or pandas Series
        Phenotype values
    output_prefix : str
        Prefix for output files

    Returns:
    --------
    DataFrame with GWAS results
    """
    # Convert inputs to numpy arrays and ensure correct dimensions
    G = np.array(G, dtype=float)
    K = np.array(K, dtype=float)
    y = np.array(phenotype, dtype=float).reshape(-1, 1)  # Make it 2D column vector

    # Create fixed effect design matrix (intercept)
    X = np.ones((G.shape[0], 1))

    print("Data shapes:")
    print(f"G: {G.shape}")
    print(f"K: {K.shape}")
    print(f"y: {y.shape}")
    print(f"X: {X.shape}")

    try:
        # Run GWAS using correct Limix interface
        print("Running GWAS...")
        gwas = limix.qtl.scan(G=G, Y=y, K=K, M=X, verbose=True)

        # Convert results to DataFrame
        results = pd.DataFrame({
            'SNP': range(G.shape[1]),
            'Pvalue': gwas.stats.pv[0],  # First column of p-values
            'Beta': gwas.stats.beta[0],   # Effect sizes
            'SE': gwas.stats.se[0]        # Standard errors
        })

        # Save results
        results.to_csv(f"{output_prefix}.csv", index=False)
        print(f"Results saved to {output_prefix}.csv")

        # Print top associations
        print("\nTop 10 associations:")
        top_results = results.nsmallest(10, 'Pvalue')
        print(top_results)

        return results

    except Exception as e:
        print(f"Error during GWAS: {str(e)}")
        print("Debugging information:")
        print(f"G contains NaN: {np.isnan(G).any()}")
        print(f"K contains NaN: {np.isnan(K).any()}")
        print(f"y contains NaN: {np.isnan(y).any()}")
        print(f"G range: {np.min(G)} to {np.max(G)}")
        print(f"K range: {np.min(K)} to {np.max(K)}")
        print(f"y range: {np.min(y)} to {np.max(y)}")
        raise

# First, check your phenotype data
print("Checking phenotype data:")
print(pheno.head())
print("\nPhenotype shape:", pheno.shape)

# If phenotype is a DataFrame with multiple columns, select one column
if isinstance(pheno, pd.DataFrame) and pheno.shape[1] > 1:
    phenotype_values = pheno.iloc[:, 0]  # Use first column
else:
    phenotype_values = pheno

# Run GWAS
results = run_gwas_simple(
    G=G,
    K=K_sub,
    phenotype=pheno,
    output_prefix="ddm1_gwas_results"
)

Checking phenotype data:
              1         2
0
10010  0.024980 -0.324621
1002  -0.049857 -0.024401
108   -0.033401  1.064215
14319 -0.040161  0.492114
15560 -0.016326  0.265559

Phenotype shape: (266, 2)
Data shapes:
G: (266, 943557)
K: (266, 266)
y: (532, 1)
X: (266, 1)
Running GWAS...

================================= QTL analysis starts ==================================

Normalising input...

failed (0.02 seconds).

========================== QTL analysis fails in 0.03 seconds ==========================

Error during GWAS: expected string or bytes-like object
Debugging information:
G contains NaN: False
K contains NaN: False
y contains NaN: False
G range: -2.0 to 2.0
K range: -0.0679109 to 5.52756
y range: -0.772384841704681 to 1.60247241607548

TypeError: expected string or bytes-like object

In [61]:
limix

In [65]:
import limix
import numpy as np
import pandas as pd

def run_gwas_simple(G, K, phenotype, output_prefix="gwas_results"):
    """
    Run GWAS using Limix with proper data type handling
    """
    # Convert inputs to numpy arrays and ensure correct dimensions
    G = np.array(G, dtype=float)
    K = np.array(K, dtype=float)
    
    # If phenotype is a DataFrame, convert to numpy array
    if isinstance(phenotype, pd.DataFrame):
        y = phenotype.values
    else:
        y = np.array(phenotype)
    
    # Ensure y is 2D
    if len(y.shape) == 1:
        y = y.reshape(-1, 1)
    
    # Create fixed effect design matrix (intercept)
    X = np.ones((G.shape[0], 1))
    
    print("Data shapes:")
    print(f"G: {G.shape}")
    print(f"K: {K.shape}")
    print(f"y: {y.shape}")
    print(f"X: {X.shape}")
    
    try:
        # Run GWAS using Limix QTL scan
        print("Running GWAS...")
        gwas = limix.qtl.scan(
            G=G,                  # SNPs
            Y=y.astype(float),    # Phenotype
            K=K,                  # Kinship matrix
            M=X,                  # Covariates
            verbose=True
        )
        
        # Convert results to DataFrame
        results = pd.DataFrame({
            'SNP': range(G.shape[1]),
            'Pvalue': gwas.stats.pv[0],
            'Beta': gwas.stats.beta[0],
            'SE': gwas.stats.se[0]
        })
        
        # Save results
        results.to_csv(f"{output_prefix}.csv", index=False)
        print(f"Results saved to {output_prefix}.csv")
        
        return results
    
    except Exception as e:
        print(f"Error during GWAS: {str(e)}")
        print("\nDebugging information:")
        print(f"G contains NaN: {np.isnan(G).any()}")
        print(f"K contains NaN: {np.isnan(K).any()}")
        print(f"y contains NaN: {np.isnan(y).any()}")
        print(f"G range: {np.min(G)} to {np.max(G)}")
        print(f"K range: {np.min(K)} to {np.max(K)}")
        print(f"y range: {np.min(y)} to {np.max(y)}")
        print("\nData types:")
        print(f"G dtype: {G.dtype}")
        print(f"K dtype: {K.dtype}")
        print(f"y dtype: {y.dtype}")
        raise

# Select first phenotype if multiple exist
if isinstance(pheno, pd.DataFrame) and pheno.shape[1] > 1:
    print(f"Multiple phenotypes detected. Using first phenotype: {pheno.columns[0]}")
    phenotype_values = pheno.iloc[:, 0]
else:
    phenotype_values = pheno

# Run GWAS
try:
    results = run_gwas_simple(
        G=G,
        K=K_sub,
        phenotype=phenotype_values,
        output_prefix="ddm1_gwas_results"
    )
    print("\nGWAS completed successfully!")
except Exception as e:
    print(f"\nGWAS failed with error: {str(e)}")

Multiple phenotypes detected. Using first phenotype: 1
Data shapes:
G: (266, 943557)
K: (266, 266)
y: (266, 1)
X: (266, 1)
Running GWAS...

================================= QTL analysis starts ==================================

Normalising input...

failed (0.01 seconds).

========================== QTL analysis fails in 0.02 seconds ==========================

Error during GWAS: expected string or bytes-like object

Debugging information:
G contains NaN: False
K contains NaN: False
y contains NaN: False
G range: -2.0 to 2.0
K range: -0.0679109 to 5.52756
y range: -0.103047150623329 to 0.533678753218824

Data types:
G dtype: float64
K dtype: float64
y dtype: float64

GWAS failed with error: expected string or bytes-like object

In [64]:
!pip install --upgrade limix

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: limix in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (3.0.4)
Requirement already satisfied: appdirs>=1.4.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (1.4.4)
Requirement already satisfied: brent-search>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: colorama>=0.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (0.4.4)
Requirement already satisfied: scipy>=1.2.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.13.1)
Requirement already satisfied: pandas!=0.25.0rc0,>=0.24.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.3)
Requirement already satisfied: glimix-core>=3.1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.1.13)
Requirement already satisfied: xarray>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2024.7.0)
Requirement already satisfied: setuptools>=41.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (58.0.4)
Requirement already satisfied: humanfriendly>=4.18 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (10.0)
Requirement already satisfied: blessings>=1.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7)
Requirement already satisfied: statsmodels>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.14.0)
Requirement already satisfied: ndarray-listener>=2.0.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.1)
Requirement already satisfied: joblib>=0.13.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.3.2)
Requirement already satisfied: monotonic>=1.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6)
Requirement already satisfied: bgen-reader>=3.0.5 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.0.8)
Requirement already satisfied: pytest-doctestplus>=0.4.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.4.0)
Requirement already satisfied: numba>=0.43.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.60.0)
Requirement already satisfied: pytest-remfiles>=0.0.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.0.2)
Requirement already satisfied: scikit-learn>=0.20.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.6.1)
Requirement already satisfied: dask[array,dataframe]>=2.5.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (2021.10.0)
Requirement already satisfied: tqdm>=4.31.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (4.64.1)
Requirement already satisfied: netcdf4>=1.5.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.7.2)
Requirement already satisfied: pandas-plink>=2.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.2.9)
Requirement already satisfied: pytest>=4.4.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (6.2.4)
Requirement already satisfied: seaborn>=0.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.13.0)
Requirement already satisfied: limix-plot>=0.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.1.2)
Requirement already satisfied: numpy-sugar>=1.4.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (1.5.3)
Requirement already satisfied: optimix>=3.0.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.0.4)
Requirement already satisfied: loguru>=0.3.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.7.2)
Requirement already satisfied: h5py>=2.9.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (3.13.0)
Requirement already satisfied: matplotlib>=3.0.3 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (3.4.3)
Requirement already satisfied: click>=7.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix) (8.0.3)
Requirement already satisfied: numpy>=1.17.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (2.0.2)
Requirement already satisfied: qtoml>=0.2.4 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.1)
Requirement already satisfied: asciitree>=0.3.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix) (0.3.3)
Requirement already satisfied: texttable>=1.6.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.7.0)
Requirement already satisfied: cachetools>=3.1.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (5.5.2)
Requirement already satisfied: cbgen>=1.0.1 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (1.0.6)
Requirement already satisfied: requests>=1.25.8 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from bgen-reader>=3.0.5->limix) (2.26.0)
Requirement already satisfied: six in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from blessings>=1.7->limix) (1.16.0)
Requirement already satisfied: cffi in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.14.6)
Requirement already satisfied: urllib3>=1.26 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.26.7)
Requirement already satisfied: pooch in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (1.8.2)
Requirement already satisfied: cloudpickle>=1.1.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (2.0.0)
Requirement already satisfied: fsspec>=0.6.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (2021.8.1)
Requirement already satisfied: packaging>=20.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (23.1)
Requirement already satisfied: partd>=0.3.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (1.2.0)
Requirement already satisfied: pyyaml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (6.0)
Requirement already satisfied: toolz>=0.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from dask[array,dataframe]>=2.5.0->limix) (0.11.1)
Requirement already satisfied: liknorm>=1.2.8 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from glimix-core>=3.1.7->limix) (1.2.10)
Requirement already satisfied: Pillow>=6.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (8.4.0)
Requirement already satisfied: adjustText>=0.7.3 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from limix-plot>=0.1.0->limix) (1.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from matplotlib>=3.0.3->limix) (1.3.1)
Requirement already satisfied: certifi in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (2021.10.8)
Requirement already satisfied: cftime in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from netcdf4>=1.5.0.1->limix) (1.6.4.post1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from numba>=0.43.1->limix) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2021.3)
Requirement already satisfied: tzdata>=2022.7 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas!=0.25.0rc0,>=0.24.2->limix) (2023.3)
Requirement already satisfied: zstandard>=0.13.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (0.23.0)
Requirement already satisfied: Deprecated>=1.2.6 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pandas-plink>=2.0.1->limix) (1.2.18)
Requirement already satisfied: pycparser in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from cffi->cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (2.20)
Requirement already satisfied: wrapt<2,>=1.10 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from Deprecated>=1.2.6->pandas-plink>=2.0.1->limix) (1.12.1)
Requirement already satisfied: locket in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages/locket-0.2.1-py3.9.egg (from partd>=0.3.10->dask[array,dataframe]>=2.5.0->limix) (0.2.1)
Requirement already satisfied: attrs>=19.2.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (21.2.0)
Requirement already satisfied: iniconfig in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.1.1)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.13.1)
Requirement already satisfied: py>=1.8.2 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (1.10.0)
Requirement already satisfied: toml in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from pytest>=4.4.1->limix) (0.10.2)
Requirement already satisfied: idna<4,>=2.5 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from requests>=1.25.8->bgen-reader>=3.0.5->limix) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /software/f2021/software/anaconda3/2021.11/lib/python3.9/site-packages (from requests>=1.25.8->bgen-reader>=3.0.5->limix) (2.0.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from scikit-learn>=0.20.3->limix) (3.2.0)
Requirement already satisfied: patsy>=0.5.2 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from statsmodels>=0.9.0->limix) (0.5.3)
Requirement already satisfied: platformdirs>=2.5.0 in /users/elizaveta.grigoreva/.local/lib/python3.9/site-packages (from pooch->cbgen>=1.0.1->bgen-reader>=3.0.5->limix) (4.3.7)

In [1]:
from limix.qtl import scan
r = scan(G, pheno, K = K_sub, lik = 'normal', A = A, A0 = A0, A1 = A1, verbose = True)

NameError: name 'G' is not defined

In [43]:
pheno

                 1         2
0
b'10010'  0.024980 -0.324621
b'1002'  -0.049857 -0.024401
b'108'   -0.033401  1.064215
b'14319' -0.040161  0.492114
b'15560' -0.016326  0.265559
...            ...       ...
b'9927'   0.015342 -0.406540
b'9933'   0.072331  0.145948
b'9938'  -0.054522  0.056299
b'9972'  -0.035694  0.254552
b'9981'  -0.006467  1.217904

[266 rows x 2 columns]

In [56]:
import limix
import numpy as np
import pandas as pd
import h5py


# 5. Run GWAS for first phenotype
y = pheno.iloc[:, 0].values.reshape(-1, 1)
X = np.ones((len(pheno), 1))  # Intercept

# Use qtl_test_lmm instead of scan
from limix.qtl import qtl_test_lmm
results = qtl_test_lmm(
    snps=G,
    pheno=pheno,
    K=K_sub,
    covs=X,
    test="lrt"
)

ImportError: cannot import name 'qtl_test_lmm' from 'limix.qtl' (/users/elizaveta.grigoreva/.local/lib/python3.9/site-packages/limix/qtl/__init__.py)

In [47]:
import limix
print(f"Limix version: {limix.__version__}")

Limix version: 3.0.4

In [55]:
pheno

              1         2
0
10010  0.024980 -0.324621
1002  -0.049857 -0.024401
108   -0.033401  1.064215
14319 -0.040161  0.492114
15560 -0.016326  0.265559
...         ...       ...
9927   0.015342 -0.406540
9933   0.072331  0.145948
9938  -0.054522  0.056299
9972  -0.035694  0.254552
9981  -0.006467  1.217904

[266 rows x 2 columns]